#!/bin/sh
pandoc docs/search.md -o docs/search.pdf \
    --resource-path=docs \
    --pdf-engine=xelatex \
    -V geometry:margin=1in \
    -V colorlinks=true \
    -V linkcolor=blue \
    -V mainfont="Inter" \
    -V monofont="JetBrains Mono" \
    -V 'monofontoptions=RawFeature=-calt'
